####################################################
# PATH
####################################################

NODE_GLOBAL_BIN="$HOME/.npm-global/bin"
USER_BIN="$HOME/bin"
TOOLBOX="$HOME/.toolbox/bin"
RODAR="$HOME/.rodar/bin"

# Specify the XDG home directory
export XDG_CONFIG_HOME=$HOME/.config

export PATH="$USER_BIN:$NODE_GLOBAL_BIN:$TOOLBOX:$RODAR:$PATH"

