# EDA brazil workspace tools
EDA_AUTO=$(mktemp -d)
eda completions zsh > $EDA_AUTO/_eda
fpath=($EDA_AUTO $fpath)

# Set title to running command
function set-title-precmd() {
  printf "\e]2;%s\a" "${PWD/#$HOME/~}"
}

function set-title-preexec() {
  printf "\e]2;%s\a" "$1"
}

autoload -Uz add-zsh-hook
add-zsh-hook precmd set-title-precmd
add-zsh-hook preexec set-title-preexec

bindkey -e

